"""Generate static pages; Python is only an authoring tool, never a runtime dependency."""
from pathlib import Path
import json, html
R=Path(__file__).resolve().parents[1]
APPS=json.loads((R/'content/apps.json').read_text(encoding='utf-8'))
BASE='https://stiiblo.github.io/zimmalabs-website/'
def icon(a,p,lazy=True):
    return f'<img class="app-icon" src="{p}assets/icons/{a["icon"]}" alt="{a["name"]}-App-Icon" width="64" height="64" loading="{ "lazy" if lazy else "eager"}">' if a['icon'] else ''
def badges(a):
    return f'<div class="badges"><span>Android · {a["android"]}</span><span>iOS · {a["ios"]}</span></div>'
def cards(p):
    return '<div class="app-grid">'+''.join(f'<article class="app-card {"featured" if a["id"]=="fotostempel" else ""}"><div class="card-top">{icon(a,p)}<span class="card-number">0{i+1}</span></div><h3>{a["name"]}</h3><p class="benefit">{a["benefit"]}</p><p>{a["description"]}</p>{badges(a)}<a class="text-link" href="{p}{a["id"]}/">Mehr erfahren <span aria-hidden="true">↗</span><span class="sr-only"> über {a["name"]}</span></a></article>' for i,a in enumerate(APPS))+'</div>'
def brand(p):
    return f'<a class="brand" href="{p}"><img src="{p}assets/zl.svg" width="48" height="48" alt=""><span>Zimma<b>Labs</b><small>Praktische Apps. Ohne Umwege.</small></span></a>'
def nav(p):
    return f'<a href="{p}apps/">Apps</a><a href="{p}#ueber-uns">Über uns</a><a href="{p}datenschutz/">Datenschutz</a><a href="{p}kontakt/">Kontakt</a>'
def home(p):
    device=''.join(f'<div class="device-row">{icon(a,p,False)}<div><strong>{a["name"]}</strong><small>{a["android"]}</small></div><span aria-hidden="true">›</span></div>' for a in APPS)
    return f'''<section class="hero"><div class="hero-copy"><p class="eyebrow">Einfach · Nützlich · Durchdacht</p><h1>Praktische Apps.<br><em>Für einen einfacheren Alltag.</em></h1><p class="lead">ZimmaLabs entwickelt fokussierte Apps für konkrete Alltagsaufgaben – durchdacht, einfach zu bedienen und auf das Wesentliche reduziert.</p><div class="platforms"><span><i aria-hidden="true">◇</i> Android <small>Veröffentlichung in Vorbereitung</small></span><span><i aria-hidden="true">◌</i> iOS <small>Geplant</small></span></div><div class="actions"><a class="button" href="apps/">Unsere Apps <span aria-hidden="true">↗</span></a><a class="button secondary" href="#ueber-uns">Über ZimmaLabs</a></div><ul class="hero-values"><li>Klare Aufgaben</li><li>Durchdachte Bedienung</li><li>Transparente Informationen</li></ul></div><div class="showcase"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="back-panel"><img src="assets/zl.svg" width="90" height="90" alt=""><p>Weniger Umwege.<br><em>Mehr Alltag.</em></p><span>ZIMMALABS</span></div><div class="device"><div class="device-notch"></div><div class="device-brand"><img src="assets/zl.svg" alt="" width="30" height="30"> ZimmaLabs</div><p class="device-label">Kleine Apps. Klare Aufgaben.</p>{device}<p class="device-bottom">Einfach. Nützlich. Durchdacht.</p></div><p class="illustration-label">Stilisierte Präsentation · keine App-Aufnahme</p></div></section><section class="portfolio"><div class="section-heading"><div><p class="eyebrow">Unsere Apps</p><h2>Vier Apps.<br><em>Ein klarer Fokus.</em></h2></div><p>Für die kleinen Aufgaben,<br>die im Alltag einen Unterschied machen.</p></div>{cards(p)}</section><section class="trust"><div><p class="eyebrow">Privatsphäre</p><p>Klare Datenschutzinformationen.</p></div><div><p class="eyebrow">Fokus</p><p>Apps für konkrete Aufgaben.</p></div><div><p class="eyebrow">Plattformen</p><p>Android im Fokus · iOS geplant.</p></div></section><section class="about" id="ueber-uns"><div><p class="eyebrow">Über ZimmaLabs</p><h2>Kleine Apps.<br><em>Klare Aufgaben.</em></h2></div><div><p class="lead">Gute Werkzeuge machen eine Sache verständlich.</p><p>ZimmaLabs entwickelt fokussierte Werkzeuge, die konkrete Aufgaben möglichst einfach lösen. Durchdacht, praxisnah und mit transparenten Informationen dazu, was eine App kann.</p><a class="text-link" href="kontakt/">Direkt Kontakt aufnehmen ↗</a></div></section>'''
PAGES={'':('ZimmaLabs – Praktische Apps. Ohne Umwege.','Fokussierte Apps für den Alltag. Android-Veröffentlichungen in Vorbereitung, iOS geplant.'),'apps/':('Unsere Apps · ZimmaLabs','FotoStempel, Kaufakte, Vertragsakte und Boxvex. Vier Apps in Vorbereitung.')}
for a in APPS:PAGES[a['id']+'/']=(a['name']+' · ZimmaLabs',a['description']+' Veröffentlichung in Vorbereitung.')
for slug,title in [('impressum/','Impressum'),('kontakt/','Kontakt'),('datenschutz/','Datenschutz'),('datenschutz/fotostempel/','Datenschutzerklärung für FotoStempel'),('datenschutz/kaufakte/','Datenschutzerklärung für Kaufakte')]:PAGES[slug]=(title+' · ZimmaLabs',title+' von ZimmaLabs, Dario Zimmari.')
PAGES['haftung/']=('Haftungs- und Nutzungshinweise · ZimmaLabs','Hinweise zur Nutzung der ZimmaLabs-Website und Anwendungen einschließlich FotoStempel, Kaufakte, Vertragsakte und Boxvex.')
for slug,(title,desc) in PAGES.items():
    p='../'*slug.count('/') if slug else './'
    legal=slug in ['haftung/','impressum/','kontakt/','datenschutz/','datenschutz/fotostempel/','datenschutz/kaufakte/']
    if not slug:body=home(p)
    elif legal:body=(R/'content'/(slug.strip('/').replace('/','-')+'.html')).read_text(encoding='utf-8')
    elif slug=='apps/':body='<div class="page-heading"><p class="eyebrow">Unsere Apps</p><h1>Vier Apps.<br><em>Einfach durchdacht.</em></h1><p class="lead">Android steht heute im Fokus. iOS ist geplant. Alle Apps befinden sich vor ihrer öffentlichen Veröffentlichung.</p></div>'+cards(p)
    else:
        a=next(a for a in APPS if a['id']+'/'==slug)
        body=f'<section class="product-intro">{icon(a,p,False)}<p class="eyebrow">{a["name"]}</p><h1>{a["benefit"]}</h1><p class="lead">{a["description"]}</p>{badges(a)}<p>Die Veröffentlichung ist in Vorbereitung. Es gibt noch keinen öffentlichen Store-Download.</p></section>'
        if a['id']=='fotostempel':body+='<div class="features"><section><p class="eyebrow">01 · Auswählen</p><h2>Deine vorhandenen Fotos.</h2><p>Ein einzelnes Bild oder mehrere Fotos gemeinsam auswählen.</p></section><section><p class="eyebrow">02 · Gestalten</p><h2>Deine Beschriftung.</h2><p>Datum, Uhrzeit, eigenen Text, Stil und Position anpassen.</p></section><section><p class="eyebrow">03 · Speichern</p><h2>Neue Kopien.</h2><p>In FotoStempel oder zusätzlich in der Galerie speichern. Die Originalfotos bleiben erhalten.</p></section></div><section class="note"><h2>Lokal bearbeiten. Bewusst teilen.</h2><p>Die Bildbearbeitung erfolgt auf deinem Gerät. Teilen ist eine ausdrücklich von dir ausgelöste Übergabe an eine andere App.</p><a href="../datenschutz/fotostempel/">Datenschutzerklärung für FotoStempel →</a></section>'
        else:body+='<section class="note"><h2>In Vorbereitung.</h2><p>Die Beschreibung zeigt die vorgesehene Ausrichtung. Details folgen zur Veröffentlichung.</p><p>App-spezifische Datenschutzhinweise sind noch nicht final und folgen erst nach Prüfung der tatsächlichen Datenflüsse.</p><a href="../kontakt/">Fragen zum Projekt? →</a></section>'
    if slug == 'fotostempel/':
        body = body.replace('</section>', '<p>Kostenlos ausprobieren · Pro einmalig. Fünf erfolgreiche neue Fotoexporte sind kostenlos; danach ermöglicht Pro unbegrenzte Exporte. Kein Abo, keine Werbung. Preis und Währung zeigt Google Play.</p></section>', 1)
    if slug == 'kaufakte/':
        body = body.replace('<p>App-spezifische Datenschutzhinweise sind noch nicht final und folgen erst nach Prüfung der tatsächlichen Datenflüsse.</p>', '<p>Die <a href="../datenschutz/kaufakte/">Kaufakte-Datenschutzerklärung</a> beschreibt die geprüften lokalen Datenflüsse sowie Google Play Billing. Kaufakte ist zum Start kostenlos installierbar: fünf Käufe kostenlos, danach einmaliges Lifetime-Pro, kein Abo und keine Werbung.</p>')
    head=f'<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{BASE+slug}"><meta property="og:type" content="website"><meta property="og:locale" content="de_DE"><meta property="og:site_name" content="ZimmaLabs"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{BASE+slug}"><link rel="icon" href="{p}assets/zl.svg" type="image/svg+xml"><link rel="stylesheet" href="{p}assets/site.css">'
    header=f'<header class="site-header"><div class="header-inner">{brand(p)}<nav class="desktop-nav" aria-label="Hauptnavigation">{nav(p)}</nav><a class="header-cta" href="{p}apps/">Unsere Apps ↗</a><details class="mobile-menu"><summary aria-label="Navigationsmenü"><span aria-hidden="true">☰</span> Menü</summary><nav aria-label="Mobile Hauptnavigation">{nav(p)}</nav></details></div></header>'
    footer=f'<footer><div class="footer-inner"><div>{brand(p)}<a class="email" href="mailto:zimmalabs@gmail.com">zimmalabs@gmail.com</a></div><nav aria-label="Weitere Informationen"><a href="{p}apps/">Apps</a><a href="{p}datenschutz/">Datenschutz</a><a href="{p}haftung/">Haftung &amp; Nutzung</a><a href="{p}impressum/">Impressum</a><a href="{p}kontakt/">Kontakt</a></nav><p>Android im Fokus<br><span>iOS geplant</span></p></div><div class="footer-line">ZimmaLabs <span>Praktische Apps. Ohne Umwege.</span></div></footer>'
    target=R/slug/'index.html';target.parent.mkdir(exist_ok=True,parents=True)
    target.write_text('<!doctype html>\n<html lang="de"><head>'+head+'</head><body><a class="skip" href="#inhalt">Zum Inhalt</a>'+header+f'<main id="inhalt" class="{ "legal" if legal else ""}">'+body+'</main>'+footer+'</body></html>\n',encoding='utf-8')
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+s+'</loc></url>' for s in PAGES)+'</urlset>\n',encoding='utf-8')
print('Generated',len(PAGES),'static pages.')
